version: "2.1"

services:
  spark-master:
    image: spark-2:2.4.5
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 173.17.2.2
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/tmp/data
    networks:
      sparknet:
        ipv4_address: "173.17.2.2"

  spark-worker-1:
    image: spark-2:2.4.5
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 173.17.2.3
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
    ports:
      - 8081:8081
    volumes:
      - ./conf/spark-worker-1:/conf
      - ./data:/tmp/data
    networks:
      sparknet:
        ipv4_address: "173.17.2.3"

networks:
  sparknet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: "173.17.2.0/24"
          gateway: "173.17.2.1"
